# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haZ1mVCC7i5-5NmKSSkzZ4BOyrIKasto
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Correct raw URL for the CSV file on GitHub
url = "https://raw.githubusercontent.com/dayanidhi116/laptop-pricing/main/laptop_pricing_dataset_base.csv"
df = pd.read_csv(url)

# Since your dataset is a laptop pricing dataset,
# it probably doesn't have 'age' or 'charges' columns.
# Check the column names first:
print(df.columns)

# For demonstration, if you want to plot a regression,
# pick two numerical columns available in the dataset.
# Example (replace 'feature1' and 'feature2' with actual columns):
# sns.regplot(x='feature1', y='feature2', data=df)

# Replace 'feature1' and 'feature2' below with actual column names you want to plot
# Here's a placeholder example if your dataset has 'price' and 'ram':
# sns.regplot(x='ram', y='price', data=df)

# Show plot
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.title('Regression Plot')
plt.show()