# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZZItZxVoRy-5fzXLIoSeobweR3zBWsx
"""

import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000.0, 60000.0, 70000.0],
    'Is_Manager': [False, True, False]
}

df = pd.DataFrame(data)

# Display data types
print(df.dtypes)