# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haZ1mVCC7i5-5NmKSSkzZ4BOyrIKasto
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Sample DataFrame simulating a housing dataset
data = {
    'waterfront': [0, 1, 0, 1, 0, 0, 1, 0, 0, 1],
    'price': [300000, 1500000, 320000, 1700000, 310000, 305000, 1600000, 330000, 340000, 1800000]
}

df = pd.DataFrame(data)

# Create a boxplot to visualize price distribution based on waterfront view
sns.boxplot(x='waterfront', y='price', data=df)

# Set plot labels for clarity
plt.xlabel('Waterfront (0 = No, 1 = Yes)')
plt.ylabel('House Price')
plt.title('Boxplot of House Prices by Waterfront View')
plt.show()