# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haZ1mVCC7i5-5NmKSSkzZ4BOyrIKasto
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Load your dataset (replace this with your actual data loading code)
# Example:
# df = pd.read_csv('your_file.csv')

# List of selected features
features = [
    "floors", "waterfront", "lat", "bedrooms", "sqft_basement",
    "view", "bathrooms", "sqft_living15", "sqft_above",
    "grade", "sqft_living"
]

# Target variable
target = "price"

# Drop missing values (optional, depending on your dataset)
df = df.dropna(subset=features + [target])

# Feature matrix (X) and target vector (y)
X = df[features]
y = df[target]

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict and compute R² on test data
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print(f"R² score on test data: {r2:.4f}")