# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haZ1mVCC7i5-5NmKSSkzZ4BOyrIKasto
"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import numpy as np

# Example synthetic data (replace with your actual data)
np.random.seed(0)
X = np.random.rand(100, 1) * 10
y = 3 * X.squeeze() ** 2 + 2 * X.squeeze() + 1 + np.random.randn(100) * 10

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply 2nd order polynomial transformation
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Create and fit Ridge regression model
ridge = Ridge(alpha=0.1)
ridge.fit(X_train_poly, y_train)

# Predict and calculate R^2 score
y_pred = ridge.predict(X_test_poly)
r2 = r2_score(y_test, y_pred)

print(f"R^2 Score on Test Data: {r2:.4f}")