# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haZ1mVCC7i5-5NmKSSkzZ4BOyrIKasto
"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import numpy as np

# Example data (replace with your actual dataset)
np.random.seed(42)
X = np.random.rand(100, 1) * 10
y = 2 * X.squeeze() ** 2 + 3 * X.squeeze() + 5 + np.random.randn(100) * 10

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a second-order polynomial feature transformer
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Create and fit Ridge regression model with alpha=0.1
ridge = Ridge(alpha=0.1)
ridge.fit(X_train_poly, y_train)

# Predict and calculate R² on the test data
y_pred = ridge.predict(X_test_poly)
r2 = r2_score(y_test, y_pred)

print(f"R² score on test data: {r2:.4f}")