# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haZ1mVCC7i5-5NmKSSkzZ4BOyrIKasto
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Load your dataset (replace with actual loading step)
# df = pd.read_csv('your_file.csv')

# Drop missing values if needed
df = df.dropna(subset=['sqft_living', 'price'])

# Feature and target
X = df[['sqft_living']]  # Feature must be 2D
y = df['price']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict and calculate R² score
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print(f"R² score on test data: {r2:.4f}")